mainweb/urls.py
from django.urls import path
from . import views

app_name = 'mainweb'

urlpatterns = [
    path('',views.index, name='index'),
    path('change_language/<lang>/',views.change_language, name='change_language'),
    path('projects/', views.projects, name='projects'),
    path('about/', views.about, name='about')
]

nullweb/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.i18n import i18n_patterns

urlpatterns = i18n_patterns(
    path('', include('mainweb.urls')),
    path('admin/', admin.site.urls),
)

mainweb/models.py
from django.db import models

# Create your models here.

mainweb/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.conf import settings
from django.http import HttpResponse
from django.utils import translation
from django.shortcuts import redirect
from django.http import HttpResponseRedirect

def change_language(request, lang):
    translation.activate(lang)
    response = HttpResponse()
    response.set_cookie(settings.LANGUAGE_COOKIE_NAME, lang)
    return render(request, 'mainweb/home.html')
    
def index(request):
    return render(request, 'mainweb/home.html')

def projects(request):
    return render(request, 'mainweb/projects.html')

def about(request):
    return render(request, 'mainweb/about.html')

mainweb/templates/base_generic.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A Software Development company with specialisation in Video Games, Python and PHP">
    <meta name="keywords" content="python, gaming, video games, python, software development" />
    <meta property="og:title" content="Nullpod Ltd - Software Development Company" />
    <meta property="og:url" content="https://www.nullpod.com" />
    <meta property="og:description" content="A Software Development company with specialisation in Video Games, Python and PHP" />
    <meta property="og:image" content="https://www.nullpod.com/static/mainweb/images/chronicles_small.png" />

    <link rel="icon"href="{% static 'mainweb/favicon.ico' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'mainweb/css/main.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;1,300&display=swap" rel="stylesheet"> 

    <!-- Mah SCRIPTS to be removed once the proper python package is used -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" type="text/css" href="{% static 'mainweb/css/all.css' %}">
    {% block title %}
      <title>nullpod</title>
    {% endblock %} 
  </head>
  <body>
    <!-- Navigation Menu -->
    {% include 'header.html' %}

    <!-- Main Content is here -->
    <div class="maincontainer">
  
        {% block content %}
        {% endblock %}

    </div>

    <!-- footer section -->
    {% include 'footer.html' %}

  </body>
</html>

mainweb/templates/footer.html
{% load static %}
<!-- footer section -->
<footer class="fixed-bottom">
  <div id="container p-4 waveparent">
      <section class="mb-5" >
          <svg xmlns="http://www.w3.org/2000/svg" 
              class="wave-top wave1"
              viewBox="0 0 1440 320" 
              preserveAspectRatio="none"
              height="400.000mm"
          >
          <path fill="#55b8b7" fill-opacity="1" d="M0,160L48,186.7C96,213,192,267,288,261.3C384,256,480,192,576,181.3C672,171,768,213,864,218.7C960,224,1056,192,1152,192C1248,192,1344,224,1392,240L1440,256L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z">
          </path>
          </svg>

          <svg xmlns="http://www.w3.org/2000/svg" 
              viewBox="0 0 1440 320" 
              preserveAspectRatio="none"
              class="wave-top wave2"
          >
              <path fill="#a6f1f0" fill-opacity="1" d="M0,128L34.3,138.7C68.6,149,137,171,206,160C274.3,149,343,107,411,101.3C480,96,549,128,617,170.7C685.7,213,754,267,823,245.3C891.4,224,960,128,1029,106.7C1097.1,85,1166,139,1234,154.7C1302.9,171,1371,149,1406,138.7L1440,128L1440,320L1405.7,320C1371.4,320,1303,320,1234,320C1165.7,320,1097,320,1029,320C960,320,891,320,823,320C754.3,320,686,320,617,320C548.6,320,480,320,411,320C342.9,320,274,320,206,320C137.1,320,69,320,34,320L0,320Z">
              </path>
          </svg>

          <svg xmlns="http://www.w3.org/2000/svg" 
              viewBox="0 0 1440 320"
              preserveAspectRatio="none"
              class="wave-top wave3">
              <path fill="#0c5453" fill-opacity="1" d="M0,224L48,218.7C96,213,192,203,288,213.3C384,224,480,256,576,256C672,256,768,224,864,208C960,192,1056,192,1152,197.3C1248,203,1344,213,1392,218.7L1440,224L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z">
              </path>
          </svg>
      </section>
  </div> 

  </footer>

<script type="application/javascript" src="{% static 'mainweb/javascript/anime.min.js' %}"></script>

<script>


const wave1 = "M0,160L48,186.7C96,213,192,267,288,261.3C384,256,480,192,576,181.3C672,171,768,213,864,218.7C960,224,1056,192,1152,192C1248,192,1344,224,1392,240L1440,256L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z",
      wave2 = "M0,128L34.3,138.7C68.6,149,137,171,206,160C274.3,149,343,107,411,101.3C480,96,549,128,617,170.7C685.7,213,754,267,823,245.3C891.4,224,960,128,1029,106.7C1097.1,85,1166,139,1234,154.7C1302.9,171,1371,149,1406,138.7L1440,128L1440,320L1405.7,320C1371.4,320,1303,320,1234,320C1165.7,320,1097,320,1029,320C960,320,891,320,823,320C754.3,320,686,320,617,320C548.6,320,480,320,411,320C342.9,320,274,320,206,320C137.1,320,69,320,34,320L0,320Z",
      wave3 = "M0,160L34.3,160C68.6,160,137,160,206,165.3C274.3,171,343,181,411,208C480,235,549,277,617,288C685.7,299,754,277,823,240C891.4,203,960,149,1029,112C1097.1,75,1166,53,1234,85.3C1302.9,117,1371,203,1406,245.3L1440,288L1440,320L1405.7,320C1371.4,320,1303,320,1234,320C1165.7,320,1097,320,1029,320C960,320,891,320,823,320C754.3,320,686,320,617,320C548.6,320,480,320,411,320C342.9,320,274,320,206,320C137.1,320,69,320,34,320L0,320Z",
      wave4 = "M0,160L48,186.7C96,213,192,267,288,261.3C384,256,480,192,576,181.3C672,171,768,213,864,218.7C960,224,1056,192,1152,192C1248,192,1344,224,1392,240L1440,256L1440,320L1392,320C1344,320,1248,320,1152,320C1056,320,960,320,864,320C768,320,672,320,576,320C480,320,384,320,288,320C192,320,96,320,48,320L0,320Z";

/*
anime({
  targets: '.wave3 > path',
  easing: 'easeInOutSine',
  duration: 7000,
  loop: true,
  d: [
    { value: [wave1, wave2, wave3,wave4] },
    { value: wave4 },
  ],
});
*/



anime({
  targets: '.wave1 > path',
  translateY: randomY(65),
  direction: 'alternate',
  loop: true,
  duration: 2000,
  easing: 'easeInOutSine'
});

anime({
  targets: '.wave2 > path',
  translateY: randomY(60),
  direction: 'alternate',
  loop: true,
  duration: 1800,
  easing: 'easeInOutSine'
});

anime({
  targets: '.wave3 > path',
  translateY: randomY(70),
  direction: 'alternate',
  loop: true,
  duration: 1700,
  easing: 'easeInOutSine'
});

function randomY(starting) {
    y = Math.floor(Math.random() * 5) + starting
    return y
}

</script>

mainweb/templates/header.html
{% load static %}
{% load i18n %}

{% block navbar %}
<!-- Navigation Menu -->
<nav class="navbar navbar-expand-sm navbar-custom navbar-dark">
    <a class="navbar-brand" href="#">
        <img class="jellyfish" src="{% static 'mainweb/images/jelly_fish.svg' %}" />
    </a>
    <span class="lang-switch"> [<a href="{% url 'mainweb:change_language' 'en'%}">EN</a> | <a href="{% url 'mainweb:change_language' 'fr'%}">FR</a>]</span>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav justify-content-right">
            <li class="nav-item"><a class="nav-link" href="{% url 'mainweb:index' %}">{% trans 'Home' %}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'mainweb:projects' %}">{% trans 'Projects' %}</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'mainweb:about' %}">{% trans 'About' %}</a></li>
        </ul>
    </div>
</nav>
{% endblock %}

mainweb/templates/mainweb/about.html
{% extends "base_generic.html" %}

{% load sass_tags %}
{% load i18n %}

{% block title %}
      <title>nullpod: {% trans 'About Us' %}</title>
{% endblock %} 

{% block content %}
<link rel="stylesheet" type="text/css" href="{% sass_src 'mainweb/css/about.scss' %}">

<div class="row mt-5">
  <div class="col col-sm-12">

      <h3 class="ml-3 about">{% trans 'About Us' %}</h3>
        <div class="textbox-custom">
              <div>{% trans 'We are a software development company based in Mauritius with specialisation in Video Games. We design everything from ground up and we take care of:' %}
                  <ul>
                    <li>{% trans 'Game concept and design' %}</li>
                    <li>{% trans 'Coding' %}</li>
                    <li>{% trans 'Visual Arts/Graphics' %}</li>
                    <li>{% trans 'Music Production and Sound Design' %}</li>
                    <li>{% trans 'Deployment to iOS, Android and Windows' %}</li>
                  </ul>
                {% trans 'We also develop custom web, mobile and desktop apps.' %} 
                {% trans 'We are a small team that masters the following tech stacks:' %}
                <ul>
                  <li>{% trans 'Python w/Django or Flask' %}</li>
                  <li>Symfony 4/5, PHP 7</li>
                  <li>React</li>
                  <li>VueJs</li>
                  <li>{% trans 'Unity Platform' %}</li>
                </ul> 
              </div>

              <h4>{% trans 'Follow Us' %}</h4>
              <div class="socialicons">
                <ul>
                  <li><a href="https://www.facebook.com/nullpod" title="Facebook"><i class="fab fa-facebook-square fa-2x"></i></a></li>
                  <li><a href="https://www.linkedin.com/company/nullpod" title="Linkedin"><i class="fab fa-linkedin fa-2x"></i></a></li>
                  <li><a href="https://www.instagram.com/nullpodltd/" title="Instagram"><i class="fab fa-instagram fa-2x"></i></a></li>
                  <li><a href="https://www.youtube.com/channel/UC0JQSZ8_L9dzAXiWht_SW9w" title="Youtube"><i class="fab fa-youtube fa-2x"></i></a></li>
                </ul>				
              </div>
              
              <h4>{% trans 'Contact Us' %}</h4>
              <div class="mb-4 contact">
                <ul>
                  <li><i class="fas fa-envelope"></i><span>jp.fortuno@nullpod.com</span></li>
                  <li><i class="fas fa-phone fa-flip-horizontal"></i><span>+230 57508958</span></li>
                </ul>
              </div>


        </div>
    </div>
</div>
{% endblock %}

mainweb/templates/mainweb/home.html
{% extends "base_generic.html" %}

{% load static %}
{% load i18n %}

{% block title %}
      <title>nullpod: {% trans 'Home' %}</title>
{% endblock %} 

{% block content %}
    <div class="row">

        <div class="d-flex flex-column justify-content-center">
            <div class="p-3 logocontainer">
                <img class="logo" src="{% static 'mainweb/images/nullpod_logo.svg' %}" />
            </div>
            <div class="p-2 text-center slogan">
                <span>&#60;play it this way&#62;</span>
            </div>
            <div class="p-2 text-center tagline">
                <span class="circlesize">
                    {% trans 'Game Design' %}
                    <span class="fas">.</span>
                    {% trans 'Web/Mobile Apps' %}
                    <span class="fas">.</span>
                    {% trans 'Music Production' %}
                </span>
            </div>
        </div>

    </div>

{% endblock %}

mainweb/templates/mainweb/projects.html
{% extends "base_generic.html" %}

{% load static %}
{% load sass_tags %}
{% load i18n %}

{% block title %}
      <title>nullpod: {% trans 'Our Projects' %}</title>
{% endblock %} 

{% block content %}


<link rel="stylesheet" type="text/css" href="{% sass_src 'mainweb/css/blog.scss' %}">
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/css/swiper.min.css">

<div class="mt-5">
    <h3 class="projects">{% trans 'Our Projects' %}</h3>

    <div class="blog-slider">
        <div class="blog-slider__wrp swiper-wrapper">
            <div class="blog-slider__item swiper-slide">

            <div class="blog-slider__img">
                <img src="{% static 'mainweb/images/chronicles.png' %}" alt="">
            </div>

            <div class="blog-slider__content">
                <span class="blog-slider__code">(Unity C#/Clip Studio Paint)</span>
                <div class="blog-slider__title">{% trans 'Codename:' %} Chronicles of Sun </div>
                <div class="blog-slider__text">
                {% trans 'We built a video game for one of our corporate clients CSR department. The official product will be launched soon. We handled most aspects of the project management, game design, visual art, sound fx and music.' %}
                </div>
                <a href="#" class="blog-slider__button">...</a>
            </div>

        </div>
        
        <div class="blog-slider__item swiper-slide">

            <div class="blog-slider__img">
                <img src="{% static 'mainweb/images/comment.png' %}" alt="">
            </div>

            <div class="blog-slider__content">
                <span class="blog-slider__code">(PHP 7/VueJs)</span>
                <div class="blog-slider__title">{% trans 'Comment System' %}</div>
                <div class="blog-slider__text">{% trans 'We revamped the Comment System of one of our clients and built a 2-level comment system from scratch using the modern VueJs framework that includes emojis, animated GIFs and images' %}</div>
                <a href="#" class="blog-slider__button">...</a>
            </div>

        </div>
            
        <div class="blog-slider__item swiper-slide">

            <div class="blog-slider__img">
                <img src="{% static 'mainweb/images/qb_lab_screen3.png' %}" alt="">
            </div>

            <div class="blog-slider__content">
                <span class="blog-slider__code">(Python Django/Bootstrap4)</span>
                <div class="blog-slider__title">Qb Lab</div>
                <div class="blog-slider__text">
                {% trans 'QB Lab Software is a custom software exclusively designed for the Laboratoire de Quatre Bornes in Mauritius using Python Django framework. QB Lab is an application that registers Patient data and Blood Tests and produces simple reports given to the patients visiting.' %}
                </div>
                <a href="#" class="blog-slider__button">...</a>
            </div>

            </div>
        </div>
        
        <div class="blog-slider__pagination"></div>
    </div>  

</div>



<script src='https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.3.5/js/swiper.min.js'></script>
<script>
    var swiper = new Swiper('.blog-slider', {
        spaceBetween: 30,
        effect: 'fade',
        loop: true,
        mousewheel: {
            invert: false,
        },
        // autoHeight: true,
        pagination: {
            el: '.blog-slider__pagination',
            clickable: true,
        }
        });
</script>

{% endblock %} 